proxy:
  port: 8080
  authentication: none
  docker:
      internal-networking: true
  specs:
  - id: 01_DNABarcodeCompatibility
    display-name: DNABarcodeCompatibility
    description: Shiny interface for DNABarcodeCompatibility
    container-cmd: ["R", "-e", "shiny::runApp('/root/DNABarcodeCompatibility_ShinyApp')"]
    container-memory: 3g
    container-image: etournay/dna_barcode_compatibility_shiny
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log